// Generated by npm run build:semantic; do not edit. Ajv 8.20.0 (MIT).
"use strict";
export const schema0 = validate20;
const schema31 = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"urn:hoh:example:board:schema:state","type":"object","properties":{"title":{"type":"string","pattern":"^[^\\r\\n]{1,120}$"},"tasks":{"type":"array","maxItems":30,"items":{"type":"object","properties":{"id":{"type":"string","pattern":"^task-[0-9]+$"},"label":{"type":"string","pattern":"^[^\\r\\n]{1,120}$"},"done":{"type":"boolean"}},"required":["id","label","done"],"additionalProperties":false}},"nextId":{"type":"integer","minimum":1}},"required":["title","tasks","nextId"],"additionalProperties":false};
const pattern4 = new RegExp("^[^\\r\\n]{1,120}$", "u");
const pattern5 = new RegExp("^task-[0-9]+$", "u");

function validate20(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="urn:hoh:example:board:schema:state" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate20.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(errors === 0){
if(data && typeof data == "object" && !Array.isArray(data)){
let missing0;
if((((data.title === undefined) && (missing0 = "title")) || ((data.tasks === undefined) && (missing0 = "tasks"))) || ((data.nextId === undefined) && (missing0 = "nextId"))){
validate20.errors = [{instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: missing0},message:"must have required property '"+missing0+"'"}];
return false;
}
else {
const _errs1 = errors;
for(const key0 in data){
if(!(((key0 === "title") || (key0 === "tasks")) || (key0 === "nextId"))){
validate20.errors = [{instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"}];
return false;
break;
}
}
if(_errs1 === errors){
if(data.title !== undefined){
let data0 = data.title;
const _errs2 = errors;
if(errors === _errs2){
if(typeof data0 === "string"){
if(!pattern4.test(data0)){
validate20.errors = [{instancePath:instancePath+"/title",schemaPath:"#/properties/title/pattern",keyword:"pattern",params:{pattern: "^[^\\r\\n]{1,120}$"},message:"must match pattern \""+"^[^\\r\\n]{1,120}$"+"\""}];
return false;
}
}
else {
validate20.errors = [{instancePath:instancePath+"/title",schemaPath:"#/properties/title/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
var valid0 = _errs2 === errors;
}
else {
var valid0 = true;
}
if(valid0){
if(data.tasks !== undefined){
let data1 = data.tasks;
const _errs4 = errors;
if(errors === _errs4){
if(Array.isArray(data1)){
if(data1.length > 30){
validate20.errors = [{instancePath:instancePath+"/tasks",schemaPath:"#/properties/tasks/maxItems",keyword:"maxItems",params:{limit: 30},message:"must NOT have more than 30 items"}];
return false;
}
else {
var valid1 = true;
const len0 = data1.length;
for(let i0=0; i0<len0; i0++){
let data2 = data1[i0];
const _errs6 = errors;
if(errors === _errs6){
if(data2 && typeof data2 == "object" && !Array.isArray(data2)){
let missing1;
if((((data2.id === undefined) && (missing1 = "id")) || ((data2.label === undefined) && (missing1 = "label"))) || ((data2.done === undefined) && (missing1 = "done"))){
validate20.errors = [{instancePath:instancePath+"/tasks/" + i0,schemaPath:"#/properties/tasks/items/required",keyword:"required",params:{missingProperty: missing1},message:"must have required property '"+missing1+"'"}];
return false;
}
else {
const _errs8 = errors;
for(const key1 in data2){
if(!(((key1 === "id") || (key1 === "label")) || (key1 === "done"))){
validate20.errors = [{instancePath:instancePath+"/tasks/" + i0,schemaPath:"#/properties/tasks/items/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key1},message:"must NOT have additional properties"}];
return false;
break;
}
}
if(_errs8 === errors){
if(data2.id !== undefined){
let data3 = data2.id;
const _errs9 = errors;
if(errors === _errs9){
if(typeof data3 === "string"){
if(!pattern5.test(data3)){
validate20.errors = [{instancePath:instancePath+"/tasks/" + i0+"/id",schemaPath:"#/properties/tasks/items/properties/id/pattern",keyword:"pattern",params:{pattern: "^task-[0-9]+$"},message:"must match pattern \""+"^task-[0-9]+$"+"\""}];
return false;
}
}
else {
validate20.errors = [{instancePath:instancePath+"/tasks/" + i0+"/id",schemaPath:"#/properties/tasks/items/properties/id/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
var valid2 = _errs9 === errors;
}
else {
var valid2 = true;
}
if(valid2){
if(data2.label !== undefined){
let data4 = data2.label;
const _errs11 = errors;
if(errors === _errs11){
if(typeof data4 === "string"){
if(!pattern4.test(data4)){
validate20.errors = [{instancePath:instancePath+"/tasks/" + i0+"/label",schemaPath:"#/properties/tasks/items/properties/label/pattern",keyword:"pattern",params:{pattern: "^[^\\r\\n]{1,120}$"},message:"must match pattern \""+"^[^\\r\\n]{1,120}$"+"\""}];
return false;
}
}
else {
validate20.errors = [{instancePath:instancePath+"/tasks/" + i0+"/label",schemaPath:"#/properties/tasks/items/properties/label/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
var valid2 = _errs11 === errors;
}
else {
var valid2 = true;
}
if(valid2){
if(data2.done !== undefined){
const _errs13 = errors;
if(typeof data2.done !== "boolean"){
validate20.errors = [{instancePath:instancePath+"/tasks/" + i0+"/done",schemaPath:"#/properties/tasks/items/properties/done/type",keyword:"type",params:{type: "boolean"},message:"must be boolean"}];
return false;
}
var valid2 = _errs13 === errors;
}
else {
var valid2 = true;
}
}
}
}
}
}
else {
validate20.errors = [{instancePath:instancePath+"/tasks/" + i0,schemaPath:"#/properties/tasks/items/type",keyword:"type",params:{type: "object"},message:"must be object"}];
return false;
}
}
var valid1 = _errs6 === errors;
if(!valid1){
break;
}
}
}
}
else {
validate20.errors = [{instancePath:instancePath+"/tasks",schemaPath:"#/properties/tasks/type",keyword:"type",params:{type: "array"},message:"must be array"}];
return false;
}
}
var valid0 = _errs4 === errors;
}
else {
var valid0 = true;
}
if(valid0){
if(data.nextId !== undefined){
let data6 = data.nextId;
const _errs15 = errors;
if(!(((typeof data6 == "number") && (!(data6 % 1) && !isNaN(data6))) && (isFinite(data6)))){
validate20.errors = [{instancePath:instancePath+"/nextId",schemaPath:"#/properties/nextId/type",keyword:"type",params:{type: "integer"},message:"must be integer"}];
return false;
}
if(errors === _errs15){
if((typeof data6 == "number") && (isFinite(data6))){
if(data6 < 1 || isNaN(data6)){
validate20.errors = [{instancePath:instancePath+"/nextId",schemaPath:"#/properties/nextId/minimum",keyword:"minimum",params:{comparison: ">=", limit: 1},message:"must be >= 1"}];
return false;
}
}
}
var valid0 = _errs15 === errors;
}
else {
var valid0 = true;
}
}
}
}
}
}
else {
validate20.errors = [{instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"}];
return false;
}
}
validate20.errors = vErrors;
return errors === 0;
}
validate20.evaluated = {"props":true,"dynamicProps":false,"dynamicItems":false};

export const schema1 = validate21;
const schema32 = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"urn:hoh:example:board:schema:setTitle","type":"object","properties":{"title":{"type":"string","pattern":"^[^\\r\\n]{1,120}$"}},"required":["title"],"additionalProperties":false};

function validate21(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="urn:hoh:example:board:schema:setTitle" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate21.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(errors === 0){
if(data && typeof data == "object" && !Array.isArray(data)){
let missing0;
if((data.title === undefined) && (missing0 = "title")){
validate21.errors = [{instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: missing0},message:"must have required property '"+missing0+"'"}];
return false;
}
else {
const _errs1 = errors;
for(const key0 in data){
if(!(key0 === "title")){
validate21.errors = [{instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"}];
return false;
break;
}
}
if(_errs1 === errors){
if(data.title !== undefined){
let data0 = data.title;
const _errs2 = errors;
if(errors === _errs2){
if(typeof data0 === "string"){
if(!pattern4.test(data0)){
validate21.errors = [{instancePath:instancePath+"/title",schemaPath:"#/properties/title/pattern",keyword:"pattern",params:{pattern: "^[^\\r\\n]{1,120}$"},message:"must match pattern \""+"^[^\\r\\n]{1,120}$"+"\""}];
return false;
}
}
else {
validate21.errors = [{instancePath:instancePath+"/title",schemaPath:"#/properties/title/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
}
}
}
}
else {
validate21.errors = [{instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"}];
return false;
}
}
validate21.errors = vErrors;
return errors === 0;
}
validate21.evaluated = {"props":true,"dynamicProps":false,"dynamicItems":false};

export const schema2 = validate22;
const schema33 = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"urn:hoh:example:board:schema:output","type":"object","properties":{"message":{"type":"string","pattern":"^[^\\r\\n]{1,240}$"}},"required":["message"],"additionalProperties":false};
const pattern8 = new RegExp("^[^\\r\\n]{1,240}$", "u");

function validate22(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="urn:hoh:example:board:schema:output" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate22.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(errors === 0){
if(data && typeof data == "object" && !Array.isArray(data)){
let missing0;
if((data.message === undefined) && (missing0 = "message")){
validate22.errors = [{instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: missing0},message:"must have required property '"+missing0+"'"}];
return false;
}
else {
const _errs1 = errors;
for(const key0 in data){
if(!(key0 === "message")){
validate22.errors = [{instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"}];
return false;
break;
}
}
if(_errs1 === errors){
if(data.message !== undefined){
let data0 = data.message;
const _errs2 = errors;
if(errors === _errs2){
if(typeof data0 === "string"){
if(!pattern8.test(data0)){
validate22.errors = [{instancePath:instancePath+"/message",schemaPath:"#/properties/message/pattern",keyword:"pattern",params:{pattern: "^[^\\r\\n]{1,240}$"},message:"must match pattern \""+"^[^\\r\\n]{1,240}$"+"\""}];
return false;
}
}
else {
validate22.errors = [{instancePath:instancePath+"/message",schemaPath:"#/properties/message/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
}
}
}
}
else {
validate22.errors = [{instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"}];
return false;
}
}
validate22.errors = vErrors;
return errors === 0;
}
validate22.evaluated = {"props":true,"dynamicProps":false,"dynamicItems":false};

export const schema3 = validate23;
const schema34 = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"urn:hoh:example:board:schema:addTask","type":"object","properties":{"label":{"type":"string","pattern":"^[^\\r\\n]{1,120}$"}},"required":["label"],"additionalProperties":false};

function validate23(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="urn:hoh:example:board:schema:addTask" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate23.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(errors === 0){
if(data && typeof data == "object" && !Array.isArray(data)){
let missing0;
if((data.label === undefined) && (missing0 = "label")){
validate23.errors = [{instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: missing0},message:"must have required property '"+missing0+"'"}];
return false;
}
else {
const _errs1 = errors;
for(const key0 in data){
if(!(key0 === "label")){
validate23.errors = [{instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"}];
return false;
break;
}
}
if(_errs1 === errors){
if(data.label !== undefined){
let data0 = data.label;
const _errs2 = errors;
if(errors === _errs2){
if(typeof data0 === "string"){
if(!pattern4.test(data0)){
validate23.errors = [{instancePath:instancePath+"/label",schemaPath:"#/properties/label/pattern",keyword:"pattern",params:{pattern: "^[^\\r\\n]{1,120}$"},message:"must match pattern \""+"^[^\\r\\n]{1,120}$"+"\""}];
return false;
}
}
else {
validate23.errors = [{instancePath:instancePath+"/label",schemaPath:"#/properties/label/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
}
}
}
}
else {
validate23.errors = [{instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"}];
return false;
}
}
validate23.errors = vErrors;
return errors === 0;
}
validate23.evaluated = {"props":true,"dynamicProps":false,"dynamicItems":false};

export const schema4 = validate24;
const schema35 = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"urn:hoh:example:board:schema:setTaskDone","type":"object","properties":{"taskId":{"type":"string","pattern":"^task-[0-9]+$"},"done":{"type":"boolean"}},"required":["taskId","done"],"additionalProperties":false};

function validate24(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="urn:hoh:example:board:schema:setTaskDone" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate24.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(errors === 0){
if(data && typeof data == "object" && !Array.isArray(data)){
let missing0;
if(((data.taskId === undefined) && (missing0 = "taskId")) || ((data.done === undefined) && (missing0 = "done"))){
validate24.errors = [{instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: missing0},message:"must have required property '"+missing0+"'"}];
return false;
}
else {
const _errs1 = errors;
for(const key0 in data){
if(!((key0 === "taskId") || (key0 === "done"))){
validate24.errors = [{instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"}];
return false;
break;
}
}
if(_errs1 === errors){
if(data.taskId !== undefined){
let data0 = data.taskId;
const _errs2 = errors;
if(errors === _errs2){
if(typeof data0 === "string"){
if(!pattern5.test(data0)){
validate24.errors = [{instancePath:instancePath+"/taskId",schemaPath:"#/properties/taskId/pattern",keyword:"pattern",params:{pattern: "^task-[0-9]+$"},message:"must match pattern \""+"^task-[0-9]+$"+"\""}];
return false;
}
}
else {
validate24.errors = [{instancePath:instancePath+"/taskId",schemaPath:"#/properties/taskId/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
var valid0 = _errs2 === errors;
}
else {
var valid0 = true;
}
if(valid0){
if(data.done !== undefined){
const _errs4 = errors;
if(typeof data.done !== "boolean"){
validate24.errors = [{instancePath:instancePath+"/done",schemaPath:"#/properties/done/type",keyword:"type",params:{type: "boolean"},message:"must be boolean"}];
return false;
}
var valid0 = _errs4 === errors;
}
else {
var valid0 = true;
}
}
}
}
}
else {
validate24.errors = [{instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"}];
return false;
}
}
validate24.errors = vErrors;
return errors === 0;
}
validate24.evaluated = {"props":true,"dynamicProps":false,"dynamicItems":false};

export const schema5 = validate25;
const schema36 = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"urn:hoh:example:board:schema:removeTask","type":"object","properties":{"taskId":{"type":"string","pattern":"^task-[0-9]+$"}},"required":["taskId"],"additionalProperties":false};

function validate25(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="urn:hoh:example:board:schema:removeTask" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate25.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(errors === 0){
if(data && typeof data == "object" && !Array.isArray(data)){
let missing0;
if((data.taskId === undefined) && (missing0 = "taskId")){
validate25.errors = [{instancePath,schemaPath:"#/required",keyword:"required",params:{missingProperty: missing0},message:"must have required property '"+missing0+"'"}];
return false;
}
else {
const _errs1 = errors;
for(const key0 in data){
if(!(key0 === "taskId")){
validate25.errors = [{instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"}];
return false;
break;
}
}
if(_errs1 === errors){
if(data.taskId !== undefined){
let data0 = data.taskId;
const _errs2 = errors;
if(errors === _errs2){
if(typeof data0 === "string"){
if(!pattern5.test(data0)){
validate25.errors = [{instancePath:instancePath+"/taskId",schemaPath:"#/properties/taskId/pattern",keyword:"pattern",params:{pattern: "^task-[0-9]+$"},message:"must match pattern \""+"^task-[0-9]+$"+"\""}];
return false;
}
}
else {
validate25.errors = [{instancePath:instancePath+"/taskId",schemaPath:"#/properties/taskId/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
}
}
}
}
else {
validate25.errors = [{instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"}];
return false;
}
}
validate25.errors = vErrors;
return errors === 0;
}
validate25.evaluated = {"props":true,"dynamicProps":false,"dynamicItems":false};

export const schema6 = validate26;
const schema37 = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"urn:hoh:example:board:schema:resetBoard","type":"object","properties":{},"required":[],"additionalProperties":false};

function validate26(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="urn:hoh:example:board:schema:resetBoard" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate26.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(errors === 0){
if(data && typeof data == "object" && !Array.isArray(data)){
for(const key0 in data){
validate26.errors = [{instancePath,schemaPath:"#/additionalProperties",keyword:"additionalProperties",params:{additionalProperty: key0},message:"must NOT have additional properties"}];
return false;
break;
}
}
else {
validate26.errors = [{instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"}];
return false;
}
}
validate26.errors = vErrors;
return errors === 0;
}
validate26.evaluated = {"props":true,"dynamicProps":false,"dynamicItems":false};
